from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('Term/Condition', views.tc, name='tc'),
    path('contact/', views.contact, name='contact'),
    path('contacts/', views.contacts, name='contacts'),
    path('contact/delete/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('about/', views.about, name='about'),
    path('search/', views.search, name='search'),
    path('search/doctor/<int:specialty_id>/', views.search_doctor, name='search_doctor'),
    path('view/doctor/<int:doctor_id>/', views.view_doctor, name='view_doctor'),
    path('booking/<int:doctor_id>/', views.booking, name='booking'),
    path('booking/appointment/', views.book_appointment, name='book_appointment'),
    path('appointment/detail/view/<int:appointment_id>/', views.appointment_detail_view, name='appointment_detail_view'),
    
    #Admin
    path('patient_login/', views.patient_login, name='patient_login'),
    path('patient_register/', views.patient_register, name='patient_register'),
    path('doctor_login/', views.doctor_login, name='doctor_login'),
    path('doctor_register/', views.doctor_register, name='doctor_register'),
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    path('dash_access/', views.dash_access, name='dash_access'),
    path('patient_list/', views.patient_list, name='patient_list'),
    path('admin_profile/', views.admin_profile, name='admin_profile'),
    path('profile/create/', views.profile_create, name='profile_create'),
    path('update/doctor/status/', views.update_doctor_status, name='update_doctor_status'),
    path('doctor_list/', views.doctor_list, name='doctor_list'),
    path('admin_reviews/', views.admin_reviews, name='admin_reviews'),
    path('admin_password/change/', views.ad_password_ch, name='ad_password_ch'),
    path('admin_specialities/', views.admin_specialities, name='admin_specialities'),
    path('add/specialities/', views.add_specialities, name='add_specialities'),
    path('update/specialities/<int:specialty_id>/', views.update_specialty, name='update_specialty'),
    path('delete/specialities/<int:specialty_id>/', views.delete_specialty, name='delete_specialty'),
    path('delete/review/<int:review_id>/', views.delete_review, name='delete_review'),
    path('forgot/admin/password/', views.admin_forgot_password, name='admin_forgot_password'),
#Doctor Routes
    path('doc_panel/', views.doc_panel, name='doc_panel'),
    path('doc_profile/', views.doc_profile, name='doc_profile'),
    path('doc_logout/', views.doc_logout, name='doc_logout'),
    path('doc_appointment/', views.doc_appointment, name='doc_appointment'),
    path('my/patient/', views.my_patient, name='my_patient'),
    path('add_payment/', views.add_payment, name='add_payment'),
    path('view/patient/<int:appointment_with_detail_id>/', views.view_patient, name='view_patient'),
    path('doctor/password/change/', views.doc_password_ch, name='doc_password_ch'),
    path('doctor/profile_add_doc/', views.profile_add_doc, name='profile_add_doc'),
    path('doctor/profile_add_doc2/', views.profile_add_doc2, name='profile_add_doc2'),
    path('doctor/profile_add_doc3/', views.profile_add_doc3, name='profile_add_doc3'),
    path('doctor/profile_add_doc4/', views.profile_add_doc4, name='profile_add_doc4'),
    path('doctor/schedule_timings/', views.schedule_timings, name='schedule_timings'),
    path('doctor/add_time_slot/', views.add_time_slot, name='add_time_slot'),
    path('doctor/forgot/password/', views.doc_forgot_password, name='doc_forgot_password'),
    path('update/appointment/status/<int:appointment_with_detail_id>/<str:status>/', views.update_appointment_status, name='update_appointment_status'),
    path('transaction/list/', views.transaction_list, name='transaction_list'),
    path('delete/transaction/<int:payment_id>/', views.delete_transaction, name='delete_transaction'),
    path('doctor/reviews/', views.doc_review, name='doc_review'),
   
    #patient url
    path('patient_panel/', views.patient_panel, name='patient_panel'),
    path('ad_logout/', views.ad_logout, name='ad_logout'),
    path('admin_appointment/', views.admin_appointment, name='admin_appointment'),
    path('admin_appointment_status/', views.admin_appointment_status, name='admin_appointment_status'),
    path('patient/profile/', views.patient_profile, name='patient_profile'),
    path('patient/add/profile/', views.add_profile, name='add_profile'),
    path('patient/logout/', views.patient_logout, name='patient_logout'),
    path('patient/change/password/', views.change_password, name='change_password'),
    path('invoice/view/<int:payment_id>/', views.invoice_view, name='invoice_view'),
    path('send/review/', views.add_review, name='add_review'),
    path('patient/forgot/password/', views.patient_forgot_password, name='patient_forgot_password'),
    # Chat urls
    path('chat/patient/<int:patient_id>/', views.chat_doctor, name='chat_doctor'),
    path('chat/<int:doctor_id>/', views.chat, name='chat'),
    path('api/check_for_updates/', views.check_for_updates, name='check_for_updates'),
]