# Generated by Django 4.2.2 on 2023-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='specialization',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='speci_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='specialization',
            name='special_image',
            field=models.ImageField(default='', upload_to='doctor/spatialization/image'),
        ),
    ]
