# Generated by Django 4.2.2 on 2023-07-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_remove_doctor_speci_id_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='special_id',
        ),
    ]
