# Generated by Django 4.2.2 on 2023-07-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_rename_specialization_doctor_special_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='special_id',
            new_name='special',
        ),
    ]
