# Generated by Django 4.2.2 on 2023-07-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0008_alter_doctor_special'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='special',
            new_name='specialization',
        ),
    ]
