# Generated by Django 4.2.2 on 2023-07-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0014_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
    ]
