# Generated by Django 4.2.2 on 2023-07-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0018_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
