# Generated by Django 4.2.2 on 2023-07-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0021_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
