# Generated by Django 4.2.2 on 2023-07-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0022_alter_review_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('message', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
